kind: Service
apiVersion: v1
metadata:
  name: todo-ui
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: todo-ui
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: todo-ui-production
spec:
  replicas: 1
  template:
    metadata:
      name: todo-ui
      labels:
        app: todo-ui
        env: production
    spec:
      containers:
      - name: todo-ui
        image: REPLACE_IMAGE_TAG
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - name: todo-ui
          containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todo-ui
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: todo-ui
          servicePort: 80
    host: todo-ui.k8s.beedemo.net